### ISSUE TITLE
Feature 1 : User can see list of Magic:The Gathering sets. 

### ISSUE THREAD

**Issue by tomxnguy** [tomxnguy/mtg-deck-builder#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to see a list of sets that Magic: The Gathering has released on the home page. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the set name to get to a list of cards from the set that they want to look. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Front Page Standard Sets](https://github.com/tomxnguy/mtg-deck-builder/assets/124644438/fcb54ddc-0c7f-4def-bc42-770adfc764f6)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
